### ISSUE TITLE
Footer links don't go to any pages

### ISSUE THREAD

**Issue by rollersteaam** [LloydTao/Hackathon-NASA-2020#3]
The footer links don't go to any pages in the application.

**Comment by rollersteaam** [comment]
@LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao @LloydTao

**Comment by rollersteaam** [comment]
This is completely unprofessional.

**Comment by lloydtao** [comment]
not my bug, not my problem
